user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

job:
    resource: "@JobBundle/Resources/config/routing.yml"
    prefix:   /

crawler:
    resource: "@CrawlerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
