JobBundle\Entity\Job:
    type: entity
    table: job
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        created:
            type: datetime
        lastUpdated:
            type: datetime
            column: last_updated
        title:
            type: string
            length: 250
        description:
            type: text
        url:
            type: string
            length: 250
        urlPath:
            type: string
            length: 250
            column: url_path
        typeContract:
            type: string
            length: 250
            column: type_contract
        salary:
            type: decimal
            precision: 10
            scale: 2
        accepted:
            type: integer
        rank:
            type: integer
    manyToMany:
        tags:
            targetEntity: Tag
            joinTable:
                name: job_tags
                joinColumns:
                    job_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id