login:
    path:     /login
    defaults: { _controller: JobBundle:Security:login }
login_check:
    path:     /login_check
    defaults: { _controller: JobBundle:Default:index }
job_homepage_locale:
    path:     /{_locale}/
    defaults: { _controller: JobBundle:Default:index, _locale: es }
    requirements:
        _locale: es|en
job_homepage:
    path:     /
    defaults: { _controller: JobBundle:Default:index, _locale: es }
job_tag:
    path:     /tags/
    defaults: { _controller: JobBundle:Default:taglist }
job_tag_create:
    path:     /tags/create
    defaults: { _controller: JobBundle:Default:tagCreate }
