crawler_homepage:
    path:     /hello/{name}
    defaults: { _controller: CrawlerBundle:Default:index }
crawler_url:
    path:     /url/{name}
    defaults: { _controller: CrawlerBundle:Default:getUrl }
