services:
#    crawler.example:
#        class: CrawlerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    crawler.crawl_url:
        class: CrawlerBundle\Model\CrawlUrl
        arguments: ["@doctrine.orm.entity_manager"]